### ISSUE TITLE
Crash in lines 1171 / 196

### ISSUE THREAD

**Issue by koppor** [carlbeech/fast-duplicate-finder#5]
```text
Input directory:\\warehouse14\homes
 FileCount 416233Traceback (most recent call last):
  File "fdf_scanner.py", line 1171, in <module>
  File "fdf_scanner.py", line 196, in ScanDirectory
OSError: [Errno 22] Invalid argument
Failed to execute script fdf_scanner
```

Do I have some strange filenames on Windows?

Would be nice if invalid filenames were just skipped.

**Comment by carlbeech** [comment]
Hi

Do you have an idea of the filenames causing the issue?
Also, can you confirm the version of python you're using...

Seems the program line in error is:
FileDB.append([filename.upper(), Filepath.replace('/','\\'), time.ctime(mtime), size, '', 'N'])

So its the filename, or file time or size...   are any of those items 'strange'?

Cheers

Carl.

**Comment by koppor** [comment]
Found the issue on my Sonology:

![grafik](https://user-images.githubusercontent.com/1366654/78328710-195cd780-7580-11ea-8691-597ee6537193.png)

Will provide a fix.

Output will be something like. And will fallback to value `0` for the timestamp.

    Timestamp is invalid for file \\WAREHOUSE14\HOMES\KOPPOR\ARCHIVE\2018\ARCHIV-IAAS-TOWER\GIT-REPOSITORIES\REST-ASSURED\XML-PATH\TARGET\GENERATED-SOURCES\GROOVY-STUBS\MAIN\COM\JAYWAY\RESTASSURED\INTERNAL\PATH\XML\XMLPRETTIFIER.JAVA

**Comment by carlbeech** [comment]
Hi

That's great - many thanks and much appreciated! - having an invalid timestamp is a strange one indeed!

Hope you're ok that your change gets put back into the main script.

Cheers

Carl.

**Comment by koppor** [comment]
> Hope you're ok that your change gets put back into the main script.

Sure, therefore I created the PR #6. - Thank you for merging in!

Script still runs...

    Total files:5398432

What a pity that there is no time estimation. ^^

**Comment by carlbeech** [comment]
Hi

Been thinking about how an estimate could be done - its more difficult 
than it sounds - yes, you could do a guesstimate based on say the first 
100 files being scanned, and then keep updating the estimate as you go 
along, however, it only performs a sha256 check if it senses that two 
files are the same - and that's where the major amount of time would be 
used - and then its based on the total IO performed.

I"ve been re-familiarising myself with the code - its been a couple of 
years since I wrote it, and it would be theoretically possible - the 
program is split into a number of phases:

* Data collection - scanning all data into an in-memory array - so its 
possible to estimate that after say 100 files - as all its gathering is 
file metadata
* Sort array - basically negligible time
* calculate checksum for different values - assuming that there's no 
saved data.

An estimate would need to affect the third phase - a pre-phase would be 
needed which effectively marked the files that would actually need a 
checksum calculation, along with the total size of the files, so the 
program would 'know' how many checksums were needed. Then, when 
checksums were calculated, the time per Kb could be calculated, and 
extrapolated to the total time - also, I suppose it would be possible to 
store the checksum calculation speed into the historic MD5 file...

I really need to re-build my python environment on my current laptop, so 
I can rebuild the stand-alone binaries based on the additional code you 
updated... I can have a re-examination of the code once thats done

All the best.

Carl.



------ Original Message ------

**Comment by koppor** [comment]
I thought, there would be a progress par module for python - similar to Java. https://github.com/ctongfei/progressbar. 

No need to rewrite the code. Just at the loop where the checksums are calculated. At the beginning, one knows the total number of files. Then, at each file where the checksum is calculcated, the progressbar is updated. The timing is calculcated by the library itself.

<img src="https://i.gyazo.com/e01943454443f90c9499c00a6c197a41.gif" width="600"/>

(Still not finished BTW)

```
Total files:5398432
 ======================================   Matching files 5153827
```

**Comment by koppor** [comment]
The coolest thing would be if the current data transfer rate would be shown. Maybe only the hashing rate. - Somehow to measure how "efficient" the transfer from the NAS to the desktop PC is.

I was wondering if one could process the hashing calculation in parallel. Split up in two halfs and checking the halfs in parallel. On the one hand, I would assume that the data transfer is the limiting factor and thus this would not help to speed up the process. On the other hand, I would assume that hashing files > 200MB can be done in parallel to transfer of small files < 1MB.

All in all an output like 

    Matching files 5166318, current file size: 100MB, current hashing speed: 5MB/s

would be nice
